# Generated by Django 2.0.7 on 2018-07-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180718_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_amount',
            field=models.IntegerField(null=True),
        ),
    ]
